export const AUTH_LOAD_FINISHED = 'AUTH_LOAD_FINISHED';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const CHANNELS_FETCH_REQUEST = 'CHANNELS_FETCH_REQUEST';
export const CHANNELS_FETCH_SUCCESS = 'CHANNELS_FETCH_SUCCESS';
export const CHANNELS_FETCH_FAILURE = 'CHANNELS_FETCH_FAILURE';

export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';

export const MESSAGES_FETCH_REQUEST = 'MESSAGES_FETCH_REQUEST';
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';
export const MESSAGES_FETCH_FAILURE = 'MESSAGES_FETCH_FAILURE';



export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const SECRETS_LOAD_REQUEST = 'SECRETS_LOAD_REQUEST';
export const SECRETS_LOAD_SUCCESS = 'SECRETS_LOAD_SUCCESS';
export const SECRETS_LOAD_FAILURE = 'SECRETS_LOAD_FAILURE';

export const USER_LOGGED_IN  = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
